<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IntermediateOutputPath>..\..\..\build\LegacyLocalData\obj\</IntermediateOutputPath>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(RestoreLockedMode)' == '' and '$(CI)' == 'true'">true</RestoreLockedMode>
    <Deterministic>true</Deterministic>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\..\..\build\LegacyLocalData\bin\Release\</OutputPath>
    <IntermediateOutputPath>..\..\..\build\LegacyLocalData\obj\Release\x64\</IntermediateOutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\..\..\build\LegacyLocalData\bin\Debug\</OutputPath>
    <IntermediateOutputPath>..\..\..\build\LegacyLocalData\obj\Debug\x64\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\LocalData\AnimationXML.cs" Link="AnimationXML.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
